name: latexplotlib
channels:
  - conda-forge
  - defaults
dependencies:
  - black
  - coverage
  - ipython
  - matplotlib
  - mypy
  - pip
  - pre-commit
  - pytest
  - pytest-cov
  - pytest-mock
  - python>=3.8
  - ruff
  - pip:
    - ruff-lsp
    - python-lsp-server
    - pylsp-mypy
    - "--editable=.[tests]"
